dist: trusty
sudo: required
script: "bundle exec rake travis"
before_script: ./bin/ci/before_build.sh
services: mongodb
rvm:
  - 2.5.0
notifications:
  email:
    - didier@nocoffee.fr
  irc: "irc.freenode.org#locomotivecms"
branches:
  only:
    - master
addons:
  chrome: stable
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver
  hosts:
    - locomotive.local

